
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Feb 10 02:49:43 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 25;
  public static final int CONST = 9;
  public static final int RSQUAREB = 29;
  public static final int NUMCONST = 3;
  public static final int CASE = 23;
  public static final int SEMI = 31;
  public static final int CONTINUE = 8;
  public static final int AND = 43;
  public static final int LT = 49;
  public static final int OR = 44;
  public static final int COMMA = 33;
  public static final int CLASS = 11;
  public static final int INC = 38;
  public static final int DIV = 41;
  public static final int ASSIGN = 30;
  public static final int IF = 20;
  public static final int DOT = 32;
  public static final int EOF = 0;
  public static final int RETURN = 16;
  public static final int RBRACKET = 28;
  public static final int NEW = 10;
  public static final int error = 1;
  public static final int MUL = 40;
  public static final int ADD = 36;
  public static final int MOD = 42;
  public static final int NEQ = 46;
  public static final int BREAK = 7;
  public static final int IDENT = 2;
  public static final int VOID = 17;
  public static final int EQ = 45;
  public static final int SWITCH = 22;
  public static final int LSQUAREB = 26;
  public static final int COLON = 35;
  public static final int LBRACE = 24;
  public static final int ELSE = 21;
  public static final int ENUM = 12;
  public static final int READ = 15;
  public static final int CHARCONST = 4;
  public static final int WHILE = 19;
  public static final int RBRACE = 27;
  public static final int BOOLCONST = 5;
  public static final int EXTENDS = 13;
  public static final int PROG = 6;
  public static final int GEQT = 48;
  public static final int QUESMART = 34;
  public static final int LEQT = 50;
  public static final int DEC = 39;
  public static final int GT = 47;
  public static final int SUB = 37;
  public static final int PRINT = 14;
  public static final int DO = 18;
}

